[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pink_motions"
readme = "README.md"
authors = [
    {name = "Stéphane Caron", email = "stephane.caron@normalesup.org"},
]
maintainers = [
    {name = "Stéphane Caron", email = "stephane.caron@normalesup.org"},
]
dynamic = ['version', 'description']
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: Robot Framework :: Library",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "clarabel",
    "loop-rate-limiters >=0.1.0",
    "matplotlib",
    "meshcat >=0.3.2",
    "meshcat-shapes >=0.3.0",
    "pin-pink >=4.4.0",
    "qpmpc >=2.6.3,<4",
    "qpsolvers >=4.3.1",
    "robot_descriptions >=3.0.0",
    "xacrodoc",
]
keywords = ["inverse", "kinematics", "pinocchio"]

[project.urls]
Homepage = "https://pink-kinematics.github.io/pink_motions/"
Documentation = "https://pink-kinematics.github.io/pink_motions/"
Source = "https://github.com/pink-kinematics/pink_motions"
Tracker = "https://github.com/pink-kinematics/pink_motions/issues"
Changelog = "https://github.com/pink-kinematics/pink_motions/blob/main/CHANGELOG.md"

[tool.coverage.run]
source = ["pink_motions"]
omit = ["*/tests/*"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[tool.pixi.pypi-dependencies]
pink_motions = { path = ".", editable = true }

[tool.pixi.dependencies]
clarabel = "*"
daqp = "*"
meshcat-python = "*"
meshcat-shapes = ">=0.3.0"
pink = ">=4.4.0"
pinocchio = ">=4.1.0"
proxsuite = "*"
python = ">=3.11"

[tool.pixi.feature.coverage.dependencies]
coverage = ">=7.0"
coveralls = ">=4.0.0"

[tool.pixi.feature.coverage.tasks]
_coverage-erase = "coverage erase"
_coverage-run = { cmd = "coverage run -m pytest tests/ -v", depends-on = ["_coverage-erase"] }
_coveralls = "coveralls --service=github"
dev-coverage = { cmd = "coverage report --include=\"pink_motions/*\"", depends-on = ["_coverage-run"] }

[tool.pixi.feature.lint.dependencies]
ruff = "*"

[tool.pixi.feature.lint.tasks]
dev-format = "ruff format ."
dev-lint = "ruff check ."

[tool.pixi.feature.py311.dependencies]
python = "3.11.*"

[tool.pixi.feature.py312.dependencies]
python = "3.12.*"

[tool.pixi.feature.py313.dependencies]
python = "3.13.*"

[tool.pixi.feature.test.dependencies]
pytest = ">=7.0"

[tool.pixi.feature.test.tasks]
dev-test = "pytest tests/ -v"

[tool.pixi.environments]
default = { solve-group = "default" }
coverage = { features = ["py312", "test", "coverage"], solve-group = "py312" }
lint = { features = ["lint"], solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
test-py311 = { features = ["test", "py311"], solve-group = "py311" }
test-py312 = { features = ["test", "py312"], solve-group = "py312" }
test-py313 = { features = ["test", "py313"], solve-group = "py313" }

[tool.pixi.tasks]
scenario = "python examples/play_scenario.py"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = ["-v", "--tb=short"]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = [
    # pyflakes
    "F",
    # pycodestyle
    "E",
    "W",
    # isort
    "I001",
    # pydocstyle
    "D"
]
ignore = [
    "D401",  # good for methods but not for class docstrings
    "D405",  # British-style section names are also "proper"!
]

[tool.ruff.lint.pydocstyle]
convention = "google"
